apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment{{ .Release.Name }}
  labels:
    {{- include "3-tier-frontend-chart.labels" . | nindent 4 }}
spec:  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "3-tier-frontend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "3-tier-frontend-chart.selectorLabels" . | nindent 8 }}
    spec:

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          
