apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-{{ .Release.Name }}
  labels:
    {{- include "3-tier-backend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "3-tier-backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
      labels:
        {{- include "3-tier-backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml  .Values.securityContext | nindent 12 }}

             